import { ChampData } from '../type';

const exampleData:ChampData[] = [{
  champName: '가렌1',
  summonerName: '1',
  src: 'url',
  frequentItems: [
    {
      name: '점화석',
      skillAccel: 10,
      englishName: 'Kindlegem',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '콜필드의 전투 망치',
      skillAccel: 10,
      englishName: "Caulfield's Warhammer",
      src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '칠흑의 양날 도끼',
      skillAccel: 25,
      englishName: 'Black Cleaver',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '태양불꽃 방패',
      skillAccel: 20,
      englishName: 'Sunfire Aegis',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '발걸음 분쇄기',
      skillAccel: 20,
      englishName: 'Stridebreaker',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '신성한 파괴자',
      skillAccel: 20,
      englishName: 'Divine Sunderer',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '삼위일체',
      skillAccel: 20,
      englishName: 'Trinity Force',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
    },
  ],
  itemsPurchased: null,
  spells: {
    D: {
      spellType: 'D',
      src: 'url',
      isOn: true,
      time: null,
    },
    F: {
      spellType: 'F',
      src: 'url',
      isOn: true,
      time: null,
    },
    R: {
      spellType: 'R',
      src: 'url',
      isOn: false,
      time: null,
      level: 0,
    },
  },
}, {
  champName: '가렌2',
  summonerName: '2',
  src: 'url',
  frequentItems: [
    {
      name: '점화석',
      skillAccel: 10,
      englishName: 'Kindlegem',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '콜필드의 전투 망치',
      skillAccel: 10,
      englishName: "Caulfield's Warhammer",
      src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '칠흑의 양날 도끼',
      skillAccel: 25,
      englishName: 'Black Cleaver',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '태양불꽃 방패',
      skillAccel: 20,
      englishName: 'Sunfire Aegis',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '발걸음 분쇄기',
      skillAccel: 20,
      englishName: 'Stridebreaker',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '신성한 파괴자',
      skillAccel: 20,
      englishName: 'Divine Sunderer',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '삼위일체',
      skillAccel: 20,
      englishName: 'Trinity Force',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
    },
  ],
  itemsPurchased: null,
  spells: {
    D: {
      spellType: 'D',
      src: 'url',
      isOn: true,
      time: null,
    },
    F: {
      spellType: 'F',
      src: 'url',
      isOn: true,
      time: null,
    },
    R: {
      spellType: 'R',
      src: 'url',
      isOn: false,
      time: null,
      level: 0,
    },
  },
}, {
  champName: '가렌3',
  summonerName: '3',
  src: 'url',
  frequentItems: [
    {
      name: '점화석',
      skillAccel: 10,
      englishName: 'Kindlegem',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '콜필드의 전투 망치',
      skillAccel: 10,
      englishName: "Caulfield's Warhammer",
      src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '칠흑의 양날 도끼',
      skillAccel: 25,
      englishName: 'Black Cleaver',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '태양불꽃 방패',
      skillAccel: 20,
      englishName: 'Sunfire Aegis',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '발걸음 분쇄기',
      skillAccel: 20,
      englishName: 'Stridebreaker',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '신성한 파괴자',
      skillAccel: 20,
      englishName: 'Divine Sunderer',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '삼위일체',
      skillAccel: 20,
      englishName: 'Trinity Force',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
    },
  ],
  itemsPurchased: null,
  spells: {
    D: {
      spellType: 'D',
      src: 'url',
      isOn: true,
      time: null,
    },
    F: {
      spellType: 'F',
      src: 'url',
      isOn: true,
      time: null,
    },
    R: {
      spellType: 'R',
      src: 'url',
      isOn: false,
      time: null,
      level: 0,
    },
  },
}, {
  champName: '가렌4',
  summonerName: '4',
  src: 'url',
  frequentItems: [
    {
      name: '점화석',
      skillAccel: 10,
      englishName: 'Kindlegem',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '콜필드의 전투 망치',
      skillAccel: 10,
      englishName: "Caulfield's Warhammer",
      src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '칠흑의 양날 도끼',
      skillAccel: 25,
      englishName: 'Black Cleaver',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '태양불꽃 방패',
      skillAccel: 20,
      englishName: 'Sunfire Aegis',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '발걸음 분쇄기',
      skillAccel: 20,
      englishName: 'Stridebreaker',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '신성한 파괴자',
      skillAccel: 20,
      englishName: 'Divine Sunderer',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '삼위일체',
      skillAccel: 20,
      englishName: 'Trinity Force',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
    },
  ],
  itemsPurchased: null,
  spells: {
    D: {
      spellType: 'D',
      src: 'url',
      isOn: true,
      time: null,
    },
    F: {
      spellType: 'F',
      src: 'url',
      isOn: true,
      time: null,
    },
    R: {
      spellType: 'R',
      src: 'url',
      isOn: false,
      time: null,
      level: 0,
    },
  },
}, {
  champName: '가렌5',
  summonerName: '5',
  src: 'url',
  frequentItems: [
    {
      name: '점화석',
      skillAccel: 10,
      englishName: 'Kindlegem',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '콜필드의 전투 망치',
      skillAccel: 10,
      englishName: "Caulfield's Warhammer",
      src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '칠흑의 양날 도끼',
      skillAccel: 25,
      englishName: 'Black Cleaver',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '태양불꽃 방패',
      skillAccel: 20,
      englishName: 'Sunfire Aegis',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '발걸음 분쇄기',
      skillAccel: 20,
      englishName: 'Stridebreaker',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '신성한 파괴자',
      skillAccel: 20,
      englishName: 'Divine Sunderer',
      src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
    },
    {
      name: '삼위일체',
      skillAccel: 20,
      englishName: 'Trinity Force',
      src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
    },
  ],
  itemsPurchased: null,
  spells: {
    D: {
      spellType: 'D',
      src: 'url',
      isOn: true,
      time: null,
    },
    F: {
      spellType: 'F',
      src: 'url',
      isOn: true,
      time: null,
    },
    R: {
      spellType: 'R',
      src: 'url',
      isOn: false,
      time: null,
      level: 0,
    },
  },
}];
export default exampleData;
