import { ChampData } from '../type';

const exampleData: ChampData[] = [
  {
    champName: '',
    summonerName: '',
    src: 'https://i.imgur.com/J5z7MMP.png',
    frequentItems: [
      {
        name: '',
        skillAccel: 0,
        englishName: '',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: ' ',
        skillAccel: 0,
        englishName: "Caulfield's Warhammer",
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '  ',
        skillAccel: 0,
        englishName: '  ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '   ',
        skillAccel: 0,
        englishName: '   ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '    ',
        skillAccel: 0,
        englishName: '    ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '     ',
        skillAccel: 0,
        englishName: '     ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '      ',
        skillAccel: 0,
        englishName: '      ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      F: {
        spellType: 'F',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      R: {
        spellType: 'R',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
        level: 0,
      },
    },
  },
  {
    champName: ' ',
    summonerName: ' ',
    src: 'https://i.imgur.com/J5z7MMP.png',
    frequentItems: [
      {
        name: '',
        skillAccel: 0,
        englishName: '',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: ' ',
        skillAccel: 0,
        englishName: "Caulfield's Warhammer",
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '  ',
        skillAccel: 0,
        englishName: '  ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '   ',
        skillAccel: 0,
        englishName: '   ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '    ',
        skillAccel: 0,
        englishName: '    ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '     ',
        skillAccel: 0,
        englishName: '     ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '      ',
        skillAccel: 0,
        englishName: '      ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      F: {
        spellType: 'F',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      R: {
        spellType: 'R',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
        level: 0,
      },
    },
  },
  {
    champName: '  ',
    summonerName: '  ',
    src: 'https://i.imgur.com/J5z7MMP.png',
    frequentItems: [
      {
        name: '',
        skillAccel: 0,
        englishName: '',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: ' ',
        skillAccel: 0,
        englishName: "Caulfield's Warhammer",
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '  ',
        skillAccel: 0,
        englishName: '  ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '   ',
        skillAccel: 0,
        englishName: '   ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '    ',
        skillAccel: 0,
        englishName: '    ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '     ',
        skillAccel: 0,
        englishName: '     ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '      ',
        skillAccel: 0,
        englishName: '      ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      F: {
        spellType: 'F',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      R: {
        spellType: 'R',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
        level: 0,
      },
    },
  },
  {
    champName: '    ',
    summonerName: '    ',
    src: 'https://i.imgur.com/J5z7MMP.png',
    frequentItems: [
      {
        name: '',
        skillAccel: 0,
        englishName: '',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: ' ',
        skillAccel: 0,
        englishName: "Caulfield's Warhammer",
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '  ',
        skillAccel: 0,
        englishName: '  ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '   ',
        skillAccel: 0,
        englishName: '   ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '    ',
        skillAccel: 0,
        englishName: '    ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '     ',
        skillAccel: 0,
        englishName: '     ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '      ',
        skillAccel: 0,
        englishName: '      ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      F: {
        spellType: 'F',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      R: {
        spellType: 'R',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
        level: 0,
      },
    },
  },
  {
    champName: '     ',
    summonerName: '     ',
    src: 'https://i.imgur.com/J5z7MMP.png',
    frequentItems: [
      {
        name: '',
        skillAccel: 0,
        englishName: '',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: ' ',
        skillAccel: 0,
        englishName: "Caulfield's Warhammer",
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '  ',
        skillAccel: 0,
        englishName: '  ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '   ',
        skillAccel: 0,
        englishName: '   ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '    ',
        skillAccel: 0,
        englishName: '    ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '     ',
        skillAccel: 0,
        englishName: '     ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
      {
        name: '      ',
        skillAccel: 0,
        englishName: '      ',
        src: 'https://i.imgur.com/J5z7MMP.png',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      F: {
        spellType: 'F',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
      },
      R: {
        spellType: 'R',
        src: 'https://i.imgur.com/J5z7MMP.png',
        isOn: false,
        time: null,
        level: 0,
      },
    },
  },
];

export default exampleData;
