import { ChampData } from '../type';

const exampleData: ChampData[] = [
  {
    champName: '제이스',
    summonerName: 'T1 Canna',
    src: 'https://opgg-static.akamaized.net/images/lol/champion/Jayce.png',
    frequentItems: [
      {
        name: '점화석',
        skillAccel: 10,
        englishName: 'Kindlegem',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '콜필드의 전투 망치',
        skillAccel: 10,
        englishName: "Caulfield's Warhammer",
        src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '칠흑의 양날 도끼',
        skillAccel: 25,
        englishName: 'Black Cleaver',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '태양불꽃 방패',
        skillAccel: 20,
        englishName: 'Sunfire Aegis',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '발걸음 분쇄기',
        skillAccel: 20,
        englishName: 'Stridebreaker',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '신성한 파괴자',
        skillAccel: 20,
        englishName: 'Divine Sunderer',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '삼위일체',
        skillAccel: 20,
        englishName: 'Trinity Force',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerTeleport.png',
        isOn: false,
        time: 324,
      },
      F: {
        spellType: 'F',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: false,
        time: 86,
      },
      R: {
        spellType: 'R',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: false,
        time: 5,
        level: 0,
      },
    },
  },
  {
    champName: '리 신',
    summonerName: '난 워낙 노빠꾸라',
    src: 'https://opgg-static.akamaized.net/images/lol/champion/LeeSin.png',
    frequentItems: [
      {
        name: '점화석',
        skillAccel: 10,
        englishName: 'Kindlegem',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '콜필드의 전투 망치',
        skillAccel: 10,
        englishName: "Caulfield's Warhammer",
        src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '칠흑의 양날 도끼',
        skillAccel: 25,
        englishName: 'Black Cleaver',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '태양불꽃 방패',
        skillAccel: 20,
        englishName: 'Sunfire Aegis',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '발걸음 분쇄기',
        skillAccel: 20,
        englishName: 'Stridebreaker',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '신성한 파괴자',
        skillAccel: 20,
        englishName: 'Divine Sunderer',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '삼위일체',
        skillAccel: 20,
        englishName: 'Trinity Force',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerSmite.png',
        isOn: false,
        time: 12,
      },
      F: {
        spellType: 'F',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: true,
        time: null,
      },
      R: {
        spellType: 'R',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: true,
        time: null,
        level: 0,
      },
    },
  },
  {
    champName: '르블랑',
    summonerName: 'Hide On Bush',
    src: 'https://opgg-static.akamaized.net/images/lol/champion/Leblanc.png',
    frequentItems: [
      {
        name: '점화석',
        skillAccel: 10,
        englishName: 'Kindlegem',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '콜필드의 전투 망치',
        skillAccel: 10,
        englishName: "Caulfield's Warhammer",
        src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '칠흑의 양날 도끼',
        skillAccel: 25,
        englishName: 'Black Cleaver',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '태양불꽃 방패',
        skillAccel: 20,
        englishName: 'Sunfire Aegis',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '발걸음 분쇄기',
        skillAccel: 20,
        englishName: 'Stridebreaker',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '신성한 파괴자',
        skillAccel: 20,
        englishName: 'Divine Sunderer',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '삼위일체',
        skillAccel: 20,
        englishName: 'Trinity Force',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerDot.png',
        isOn: true,
        time: null,
      },
      F: {
        spellType: 'F',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: true,
        time: null,
      },
      R: {
        spellType: 'R',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: true,
        time: null,
        level: 0,
      },
    },
  },
  {
    champName: '징크스',
    summonerName: 'T1 Gumayusi',
    src: 'https://opgg-static.akamaized.net/images/lol/champion/Jinx.png',
    frequentItems: [
      {
        name: '점화석',
        skillAccel: 10,
        englishName: 'Kindlegem',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '콜필드의 전투 망치',
        skillAccel: 10,
        englishName: "Caulfield's Warhammer",
        src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '칠흑의 양날 도끼',
        skillAccel: 25,
        englishName: 'Black Cleaver',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '태양불꽃 방패',
        skillAccel: 20,
        englishName: 'Sunfire Aegis',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '발걸음 분쇄기',
        skillAccel: 20,
        englishName: 'Stridebreaker',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '신성한 파괴자',
        skillAccel: 20,
        englishName: 'Divine Sunderer',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '삼위일체',
        skillAccel: 20,
        englishName: 'Trinity Force',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerHeal.png',
        isOn: false,
        time: 124,
      },
      F: {
        spellType: 'F',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: false,
        time: 208,
      },
      R: {
        spellType: 'R',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: false,
        time: 86,
        level: 0,
      },
    },
  },
  {
    champName: '쓰레쉬',
    summonerName: 'T1 Keria',
    src: 'https://opgg-static.akamaized.net/images/lol/champion/Thresh.png',
    frequentItems: [
      {
        name: '점화석',
        skillAccel: 10,
        englishName: 'Kindlegem',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3067.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '콜필드의 전투 망치',
        skillAccel: 10,
        englishName: "Caulfield's Warhammer",
        src: 'https://opgg-static.akamaized.net/images/lol/item/3133.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '칠흑의 양날 도끼',
        skillAccel: 25,
        englishName: 'Black Cleaver',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3071.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '태양불꽃 방패',
        skillAccel: 20,
        englishName: 'Sunfire Aegis',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3068.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '발걸음 분쇄기',
        skillAccel: 20,
        englishName: 'Stridebreaker',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6631.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '신성한 파괴자',
        skillAccel: 20,
        englishName: 'Divine Sunderer',
        src: 'https://opgg-static.akamaized.net/images/lol/item/6632.png?image=q_auto:best&v=1626880099',
      },
      {
        name: '삼위일체',
        skillAccel: 20,
        englishName: 'Trinity Force',
        src: 'https://opgg-static.akamaized.net/images/lol/item/3078.png?image=q_auto:best&v=1626880099',
      },
    ],
    itemsPurchased: null,
    spells: {
      D: {
        spellType: 'D',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerExhaust.png',
        isOn: true,
        time: null,
      },
      F: {
        spellType: 'F',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: false,
        time: 212,
      },
      R: {
        spellType: 'R',
        src: 'http://ddragon.leagueoflegends.com/cdn/11.16.1/img/spell/SummonerFlash.png',
        isOn: false,
        time: 103,
        level: 1,
      },
    },
  },
];

export default exampleData;
